language: node_js
node_js:
  - '6'
sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-upstart
    packages:
    - mongodb-org-server
before_install:
  - npm install -g npm@4
before_script:
  - npm run test:build
  - cp config.json.example config.json
  - if [ $REQUIRES_SERVER ]; then until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done; export DISPLAY=:99;
after_script:
  - ./node_modules/.bin/lcov-result-merger 'coverage/**/*.info' | ./node_modules/coveralls/bin/coveralls.js
script: npm run $TEST
env:
  matrix:
    - TEST="lint"
    - TEST="test:api-v3" REQUIRES_SERVER=true
    - TEST="test:sanity"
    - TEST="test:content"
    - TEST="test:common"
    - TEST="test:karma"
    - TEST="client:unit"
