language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
    - build-essential
    - python
    - make
before_install:
  - npm install -g npm@4
before_script:
  - npm run test:build
  - cp config.json.example config.json
after_script:
  - ./node_modules/.bin/lcov-result-merger 'coverage/**/*.info' | ./node_modules/coveralls/bin/coveralls.js
script: npm run $TEST
env:
  matrix:
    - TEST="lint"
    - TEST="test:api-v3" REQUIRES_SERVER=true
    - TEST="test:sanity"
    - TEST="test:content"
    - TEST="test:common"
    - TEST="test:karma"
    - TEST="client:unit"
